"""Generate docs/magics.md from the live magic registry.

    python scripts/gen_magic_docs.py          # write the file
    python scripts/gen_magic_docs.py --check  # fail if it's out of date (used in CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

from ember.magics import CELL_MAGICS, LINE_MAGICS

TARGET = Path(__file__).resolve().parent.parent / "docs" / "magics.md"
ORDER = ["general", "namespace & inspection", "running & timing", "history & session", "shell & files", "gui & plotting"]


def render() -> str:
    groups: dict[str, dict[int, dict]] = {}
    for table, prefix in ((LINE_MAGICS, "%"), (CELL_MAGICS, "%%")):
        for name, spec in table.items():
            if spec.user or spec.category == "aliases":
                continue
            entry = groups.setdefault(spec.category, {}).setdefault(id(spec.fn), {"names": [], "spec": spec})
            entry["names"].append(prefix + name)

    lines = [
        "# Magic reference",
        "",
        "<!-- Generated by scripts/gen_magic_docs.py — do not edit by hand. -->",
        "",
        "Magics are commands that start with `%` (line magics) or `%%` (cell magics, on the first line of a cell).",
        "With automagic on (the default), line magics also work without the `%` when the name isn't a Python variable.",
        "Inside ember, `%help name` shows the same details.",
        "",
    ]
    for category in sorted(groups, key=lambda c: ORDER.index(c) if c in ORDER else len(ORDER)):
        lines += [f"## {category.capitalize()}", ""]
        for entry in sorted(groups[category].values(), key=lambda e: e["names"][0].lstrip("%")):
            spec = entry["spec"]
            names = ", ".join(f"`{n}`" for n in entry["names"])
            lines.append(f"### {names}")
            lines.append("")
            lines.append(spec.doc[0].upper() + spec.doc[1:] + ".")
            if spec.usage and spec.usage.strip() != spec.doc:
                lines += ["", "```text", spec.usage.strip(), "```"]
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != content:
            print("docs/magics.md is out of date — run: python scripts/gen_magic_docs.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(content)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
